eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8769/eureka/
    healthcheck:
      enabled:  true
    registry-fetch-interval-seconds: 30
zs: wwzl
